### ISSUE TITLE
some expection happen when connect etcd v3

### ISSUE THREAD

**Issue by leiax00** [tsonglew/intellij-etcdhelper#75]
**Describe the bug**

**To Reproduce**
1. add new connection
2. input :  etcd uri , user and password
3. click ok, but nothing hanpen
4. restart idea, click etcdhlper sidebar , get error: 
```
com.intellij.diagnostic.PluginException: Cannot init toolwindow com.github.tsonglew.etcdhelper.window.MainToolWindowFactory@7ca1e7a1 [Plugin: com.github.tsonglew.etcdhelper]
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.registerToolWindows(ToolWindowSetInitializer.kt:188)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.access$registerToolWindows(ToolWindowSetInitializer.kt:1)
	at com.intellij.toolWindow.ToolWindowSetInitializer$createAndLayoutToolWindows$entries$1.invokeSuspend(ToolWindowSetInitializer.kt:125)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:194)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:456)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:122)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:788)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:758)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:666)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$7(IdeEventQueue.kt:570)
	at com.intellij.openapi.application.impl.ApplicationImpl.withoutImplicitRead(ApplicationImpl.java:1446)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:570)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:994)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:994)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.util.ServiceConfigurationError: io.grpc.LoadBalancerProvider: io.grpc.util.OutlierDetectionLoadBalancerProvider not a subtype
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1244)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at io.grpc.ServiceProviders.loadAll(ServiceProviders.java:67)
	at io.grpc.LoadBalancerRegistry.getDefaultRegistry(LoadBalancerRegistry.java:102)
	at io.grpc.internal.AutoConfiguredLoadBalancerFactory.<init>(AutoConfiguredLoadBalancerFactory.java:53)
	at io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:640)
	at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:630)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:297)
	at io.vertx.grpc.VertxChannelBuilder.build(VertxChannelBuilder.java:302)
	at io.etcd.jetcd.impl.ClientConnectionManager.getChannel(ClientConnectionManager.java:89)
	at io.etcd.jetcd.impl.ClientConnectionManager.newStub(ClientConnectionManager.java:121)
	at io.etcd.jetcd.impl.KVImpl.<init>(KVImpl.java:51)
	at io.etcd.jetcd.impl.ClientImpl.lambda$new$0(ClientImpl.java:48)
	at io.etcd.jetcd.support.MemorizingClientSupplier.get(MemorizingClientSupplier.java:37)
	at io.etcd.jetcd.impl.ClientImpl.getKVClient(ClientImpl.java:65)
	at com.github.tsonglew.etcdhelper.client.impl.EtcdClient.<init>(EtcdClient.kt:71)
	at com.github.tsonglew.etcdhelper.client.impl.EtcdClient.<init>(EtcdClient.kt:45)
	at com.github.tsonglew.etcdhelper.common.ConnectionManager.addConnectionToList(ConnectionManager.kt:95)
	at com.github.tsonglew.etcdhelper.common.ConnectionManager.initConnections(ConnectionManager.kt:71)
	at com.github.tsonglew.etcdhelper.window.MainToolWindow.<init>(MainToolWindow.kt:88)
	at com.github.tsonglew.etcdhelper.window.MainToolWindowFactory.createToolWindowContent(MainToolWindowFactory.kt:42)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded(ToolWindowImpl.kt:548)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.scheduleContentInitializationIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:527)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doShowWindow(ToolWindowManagerImpl.kt:983)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl(ToolWindowManagerImpl.kt:920)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl$default(ToolWindowManagerImpl.kt:906)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.registerToolWindow$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:1094)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.registerToolWindows(ToolWindowSetInitializer.kt:176)
	... 39 more
```
**Expected behavior**
can connect etcd server correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/25100081/230708567-53c789ce-e2b5-47a8-9255-ed00117a6e43.png)
![image](https://user-images.githubusercontent.com/25100081/230708594-188ef99f-8132-4b3c-8cce-c4cf88dd49ec.png)

**Desktop (please complete the following information):**
 - OS: win11
 - Version: IntelliJ IDEA 2023.1 (Ultimate Edition) Build #IU-231.8109.175, built on March 28, 2023
 - ETCD server: 3.5.5

**Additional context**

**Comment by tsonglew** [comment]
@leiax00 Thanks for your report. I just uploaded version 1.3.1 to make intellij-etcdhelper compatible with IDEA 2023.1, and it usually takes two business day for jetbrains team to review the new version. Please take another try later, and let me know if the bug still exists.

**Comment by tsonglew** [comment]
To install 1.3.1 right away, please download the zip from [1.3.1 Release](https://github.com/tsonglew/intellij-etcdhelper/releases/tag/1.3.1), and install from disk in IDEA.

![image](https://user-images.githubusercontent.com/14333766/230760327-79e0641d-9139-4ecd-8783-1ddbc5e3338f.png)

**Comment by leiax00** [comment]
The issue has been resolved. thanks
