### ISSUE TITLE
Crash on add new connection

### ISSUE THREAD

**Issue by m-presnov** [tsonglew/intellij-etcdhelper#88]
**Describe the bug**
Try to add new connection (press '**+**' button) and have the exception:
```
java.lang.NoSuchMethodError: 'com.intellij.ui.dsl.builder.Cell com.intellij.ui.dsl.builder.Row$DefaultImpls.cell$default(com.intellij.ui.dsl.builder.Row, javax.swing.JComponent, javax.swing.JComponent, int, java.lang.Object)'
	at com.github.tsonglew.etcdhelper.dialog.EtcdConnectionSettingsDialog$createCenterPanel$4$1.invoke(EtcdConnectionSettingsDialog.kt:128)
	at com.github.tsonglew.etcdhelper.dialog.EtcdConnectionSettingsDialog$createCenterPanel$4$1.invoke(EtcdConnectionSettingsDialog.kt:128)
	at com.intellij.ui.dsl.builder.impl.PanelImpl.row(PanelImpl.kt:57)
	at com.intellij.ui.dsl.builder.impl.PanelImpl.row(PanelImpl.kt:44)
	at com.intellij.ui.dsl.builder.impl.PanelImpl.row(PanelImpl.kt:19)
	at com.github.tsonglew.etcdhelper.dialog.EtcdConnectionSettingsDialog$createCenterPanel$4.invoke(EtcdConnectionSettingsDialog.kt:128)
	at com.github.tsonglew.etcdhelper.dialog.EtcdConnectionSettingsDialog$createCenterPanel$4.invoke(EtcdConnectionSettingsDialog.kt:127)
	at com.intellij.ui.dsl.builder.BuilderKt.panel(builder.kt:19)
	at com.github.tsonglew.etcdhelper.dialog.EtcdConnectionSettingsDialog.createCenterPanel(EtcdConnectionSettingsDialog.kt:127)
	at com.intellij.openapi.ui.DialogWrapper.init(DialogWrapper.java:1323)
	at com.github.tsonglew.etcdhelper.dialog.EtcdConnectionSettingsDialog.<init>(EtcdConnectionSettingsDialog.kt:70)
	at com.github.tsonglew.etcdhelper.dialog.EtcdConnectionSettingsDialog.<init>(EtcdConnectionSettingsDialog.kt:47)
	at com.github.tsonglew.etcdhelper.action.ConnectionAddAction$Companion$create$1$1.invoke(ConnectionAddAction.kt:64)
	at com.github.tsonglew.etcdhelper.action.ConnectionAddAction$Companion$create$1$1.invoke(ConnectionAddAction.kt:63)
	at com.github.tsonglew.etcdhelper.action.CustomAction.actionPerformed(CustomAction.kt:49)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:227)
	at com.intellij.openapi.actionSystem.impl.ActionButton.lambda$performAction$2(ActionButton.java:206)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:381)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:206)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:524)
	at java.desktop/java.awt.Component.processEvent(Component.java:6422)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4969)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4583)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4524)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2809)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:794)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:766)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:764)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:695)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:635)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:580)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:75)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:67)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:580)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:72)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:355)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:354)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:793)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1014)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:114)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1014)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:349)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:848)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:391)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```

**To Reproduce**
1. Launch IntelliJ IDEA
2. Click on '**+**' button in EtcdHelper view
3. See error

**Expected behavior**
A new connection dialog should be displayed.

**Desktop:**
 - OS: Windows 10
 - Version 1.4.1
 - IntelliJ IDEA 2023.3.2 (Community Edition)

**Comment by tsonglew** [comment]
@m-presnov Hi Michael, thanks for reporting this issue! Version 1.4.2 was just uploaded to make it compatible with IDEA 2023.3, and it usually takes two business days for jetbrains team to review the new version. Please take another try later, and let me know if the bug still exists.

To install the latest version, plz refer to [Install Intellij-etcdhelper Manually](https://github.com/tsonglew/intellij-etcdhelper?tab=readme-ov-file#manually)
